### ISSUE TITLE
Variable Expiration

### ISSUE THREAD

**Issue by ahmetkarakaya** [jhalterman/expiringmap#11]
I could not find a Map object having put method with 4 parameter passing.

**Comment by jhalterman** [comment]
Not sure exactly which method you're describing?

**Comment by ahmetkarakaya** [comment]
For the example of  Variable Expiration, I cannot find map.put with four parameters 

Map<String, String> map = ExpiringMap.builder()
  .variableExpiration()
  .build();

map.put("foo", "bar", ExpirationPolicy.ACCESSED, 5, TimeUnit.SECONDS);

**Comment by jhalterman** [comment]
Thanks for bringing this up. This was just an error in the docs. Try assigning to `ExpiringMap` instead:
```
ExpiringMap map = ExpiringMap.builder()
.variableExpiration()
.build();
```
