### ISSUE TITLE
Builder constructor has private access

### ISSUE THREAD

**Issue by AGausmann** [jhalterman/expiringmap#13]
This is something that really bugs me. Why abstract the `Builder` constructor to a function, which in turn, provides no way of defining generic types? This leads to problems when `EntryLoader` needs to know type parameters - this code will fail to compile:

```java
Map<String, Object> objectMap = ExpiringMap.builder() // This is Builder<Object, Object>
        .entryLoader(new EntryLoader<String, Object>() { ... }) // This is EntryLoader<String, Object>
        .build();
```

As stated, the simplest fix is to grant access to the builder's constructor, which would allow us to supply generic types. If there is a way around this problem, please let me know.

**Comment by jhalterman** [comment]
I don't remember exactly why I did this, but probably since the builder is meant to be used in an entire sequence, terminated with a `build()` call, which is where the type inference happens:

```
    Map<String, Object> objectMap = ExpiringMap.builder() 
      .entryLoader(new EntryLoader<String, Object>() {
        @Override
        public Object load(String key) {
          return null;
        }
      }).build();
```

FWIW, other things like Guava's [CacheBuilder](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/cache/CacheBuilder.html#newBuilder()) do the same.

**Comment by AGausmann** [comment]
You're right, I meant to complete the statement with `.build();`. That snippet is fixed now. However, the problem still stands, even if the statement ends with building the map.

**Comment by AGausmann** [comment]
Update: Apparently, I had a syntax error elsewhere that had cut the final build call. I'm surprised I didn't catch it beforehand. It supposedly works fine now.
