### ISSUE TITLE
Revenge of a copied code

### ISSUE THREAD

**Issue by pow45372** [jhalterman/expiringmap#15]
In notifyListeners() there is a triple copy of a code for calling expired(). One of them, at
https://github.com/jhalterman/expiringmap/blob/master/src/main/java/net/jodah/expiringmap/ExpiringMap.java#L1078
lacks try-catch block. An exception occuring there breaks the whole map when expiring an entry - it fails to schedule the next expiration.

**Comment by jhalterman** [comment]
This was not copied code, but a bug nonetheless. Thanks.
