### ISSUE TITLE
improvement on Assert

### ISSUE THREAD

**Issue by mawulf** [jhalterman/expiringmap#21]
Hi,
do you think, it's an improvement to make use of the standardized Objects class to check if a parameter/Object is null?
Example:
```Objects.requireNonNull(listener, "listener cannot be null");```
instead of 
```Assert.notNull(listener, "listener");```

**Comment by jhalterman** [comment]
Probably not much of an improvement since the `Objects` class still doesn't have the other assertions I need and the full error message has to be repeated for each assertion. Anyways, ExpiringMap is currently targeted at JDK 1.6 which I don't think had the Objects class.
