### ISSUE TITLE
OSGi bundle?

### ISSUE THREAD

**Issue by CodingFabian** [jhalterman/expiringmap#23]
Hi,
I would like to use this neat library as an OSGi bundle. Would you be willing to accept a PR changing the build to produce one? (it actually only adds manifest headers)

**Comment by jhalterman** [comment]
Hi Fabian - That would be great if you want to send over a PR. Ideally maven should be able to generate a manifest so that we never have to edit it by hand if any packages changes in the future.

**Comment by jhalterman** [comment]
0.5.2 has been released with this. Thanks for the contribution!

**Comment by CodingFabian** [comment]
Cool, thanks for the quick turnaround.
