### ISSUE TITLE
Java documentation gives wrong time complexity

### ISSUE THREAD

**Issue by diedirk** [jhalterman/expiringmap#25]
This is my first time logging an issue. Please bare with me if I'm not following the correct process.

The Java documentation for Expiring map says:
"put/remove operations are constant O(n). When variable expiration is enabled, put/remove operations impose an O(log n) cost."

Believe that should be O(1) instead of O(log n).

**Comment by jhalterman** [comment]
Thanks for pointing this out. It was previously fixed in the README but not in the javadocs. Should be O(1) unless using variable expiration, then it's O(log n) (since TreeSet is used internally).
