### ISSUE TITLE
containsAll()

### ISSUE THREAD

**Issue by sbrattla** [jhalterman/expiringmap#28]
I have not had time to look closer into why this is, but it seems that containsAll() on the Collection returned by values() does not work properly.

If i exchange the expiringmap with an "org.apache.commons.collections4.map.PassiveExpiringMap", things work fine.

**Comment by jhalterman** [comment]
Just pushed the 0.5.3 release which fixes this. Thanks for reporting.

**Comment by sbrattla** [comment]
Thanks for a really quick response!
