### ISSUE TITLE
setExpiration Throws a nullpointer if you attempt to set the expiration for a non-existing entry

### ISSUE THREAD

**Issue by philippe-cm** [jhalterman/expiringmap#31]
setExpiration Throws a nullpointer if you attempt to set the expiration for a non-existing entry.

If the map doesn't have an entry which is mapped to the given key entries.get(key) will return null and then it will attempt to set the expiration time on a null object. 

https://github.com/jhalterman/expiringmap/blob/master/src/main/java/net/jodah/expiringmap/ExpiringMap.java#L1068

Just had this problem because I was using the wrong map but I am assuming it would happen if your entry expired before or as you try to setExpiration for that expired entry.

**Comment by jhalterman** [comment]
Thanks for filing this. Fixed!
