### ISSUE TITLE
EntryLoader/ExpiringEntryLoader executed multiple times under high concurrency

### ISSUE THREAD

**Issue by peter-fu** [jhalterman/expiringmap#33]
Seems caused by missing locking mechanism in `ExpiringMap.get()` when `EntryLoader`/`ExpiringEntryLoader` was introduced.

Workaround: make `ExpiringMap.get()` `synchronized` - just a dirty hack.
https://github.com/peter-fu/expiringmap/commit/fa370a52e5e16151f031e5dff321ef5d4c1775a3

**Comment by jhalterman** [comment]
@peter-fu Can you describe a scenario that would allow me to reproduce this?

**Comment by jhalterman** [comment]
Nvm - I reproduced it. Thanks for reporting this!

**Comment by peter-fu** [comment]
Wow, magics!!

Thanks a lot for fixing this.

**Comment by jhalterman** [comment]
Sure - I'm releasing 0.5.6 right now. It should be in maven central in a few hours.
