### ISSUE TITLE
Implementing loaders for values?

### ISSUE THREAD

**Issue by fge** [jhalterman/expiringmap#4]
I'm a fan of Guava's LoadingCache but it misses exactly what this implementation offers: variable entry expiry.

But... This project lacks one thing LoadingCache has, and that is loaders for values (depending on the key).

It is planned in the future to add this functionality? Ideally, with a checked and unchecked get method? (well, unchecked there is already and that's .get())

**Comment by jhalterman** [comment]
@fge Are you satisfied with this change?

**Comment by fge** [comment]
Sorry I didn't answer earlier.

It looks fine to me... Do you want me to test it in any way?

**Comment by jhalterman** [comment]
Only if you want. I just wanted to make sure the API change looked good to you since it was your request :)

**Comment by jhalterman** [comment]
Sure!

**Comment by fge** [comment]
Sorry, but it may take longer than expected :/ At the moment I can't instantiate a Builder without having to specify parameter types...

I'll delve into the problem some more; it is a problem worth solving.

**Comment by jhalterman** [comment]
If you come across any fixes for the builder or anything else, feel free to send over a PR along with a test case.
