### ISSUE TITLE
Year 2016 at the end of the readme should be 2017 by now?

### ISSUE THREAD

**Issue by mrtnkbnn** [jhalterman/expiringmap#46]
Just noticed that readme ends with
> Copyright 2009-2016 Jonathan Halterman - Released under the Apache 2.0 license.

But as it is 2017 already it should be
> Copyright 2009-2017 Jonathan Halterman - Released under the Apache 2.0 license.

**Comment by jhalterman** [comment]
Keeping copyrights up to date is a never ending process. Feel free to send a PR :)
