### ISSUE TITLE
Expiring list and queue implementations

### ISSUE THREAD

**Issue by savinov** [jhalterman/expiringmap#6]
Hi!

Do you plan to implement expiring list and queue collections additionaly to expiring map?

**Comment by jhalterman** [comment]
No plans to do lists. One of the nice things about maps are that the internal order doesn't matter to the user, unless it's a `SortedMap`, which ExpiringMap is not. This allows me to control the internal ordering of elements based on expiration time. With a list I couldn't do that - so tracking of element expiration times would have to be done in a separate internal data structure, which is unfortunate.

**Comment by apkelly** [comment]
Wouldn't LinkedList allow you to specify the ordering? When an element is accessed you could just move that to the head of the list to keep the list in expiration order (assuming the expiration strategy is access and not created).

**Comment by jhalterman** [comment]
@apkelly That's a good point re: LinkedList. Building one is something I'm just not interested in though - too little time with other projects :)
