### ISSUE TITLE
ConcurrentModificationException while iterating ExpiringMap with ACCESSED expiration policy

### ISSUE THREAD

**Issue by savinov** [jhalterman/expiringmap#7]
How can I iterate ExpiringMap with ACCESS expiration policy?

Here is a test to get ConcurrentModificationException:

```java
public void test() {
    ExpiringMap<String, String> map = ExpiringMap.builder().expiration(10, TimeUnit.MINUTES)
            .expirationPolicy(ExpiringMap.ExpirationPolicy.ACCESSED).build();
    map.put("k1", "v1");
    map.put("k2", "v2");
    for (Object key : map.keySet()) {
        String val = map.get(key);
        System.out.printf("key:" + key + " val:" + val);
    }
}
```

The exception throws at the second iteration, first iteration doesn't throw the exception.

It's possible to itrate values by using valuesIterator() method, but how to link key to value in this case?

**Comment by jhalterman** [comment]
I just pushed commit 476a93431d8d1271381d04c0bc8b4e88f152466e which adds proper support for `entrySet()`, `keySet()` and `values()`. You should now be able to use `entrySet().iterator()` to avoid any ConcurrentModificationExceptions.

**Comment by savinov** [comment]
Thanks, I'll try it.
