### ISSUE TITLE
Add a method to get the actual time remaining to expiration

### ISSUE THREAD

**Issue by lapo-luchini** [jhalterman/expiringmap#8]
Originally I thought (hoped) that `getExpiration(key)` would give me the remaining expiration time for the element, while it is returning the initial expiration time.
It would be nice to have a method to get that, too; right now I'm wrapping the value with an object that contains that, but it is a duplicate and not so trustworthy as a value.

**Comment by jhalterman** [comment]
Your commit looks good to me. See my comment there.
